name: Update Waline TCB

on: 
  workflow_dispatch:
  push:
    branches: main

jobs:
  build:
    name: Update Waline TCB
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@main
      - name: Setup Node.js 10.x
        uses: actions/setup-node@main
        with:
         node-version: "10.x"
      - name: Run
        run: |
          git clone https://github.com/walinejs/tcb-starter.git
          npm i -g @cloudbase/cli
          tcb login --apiKeyId "${{ secrets.SECRETID }}" --apiKey "${{ secrets.SECRETKEY }}"
          tcb fn deploy "waline" -e "${{ secrets.TCBENVID }}" --force --dir ./tcb-starter
      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
      - name: Telegram Notification
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          botToken: ${{ secrets.TG_BOT_TOKEN }}
          chatId: ${{ secrets.TG_CHAT_ID }}
          jobStatus: ${{ job.status }}
          skipSuccess: false
